version: "3"

services:
  # The Application (PHP)
  php:
    image: thecodingmachine/php:7.4-v3-fpm-node12
    working_dir: /var/www
    container_name: kado_php
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
    environment:
      DB_PORT: 3306
      DB_HOST: db
    networks:
      - network

  # The Web Server (Nginx)
  nginx:
    build:
      context: ./infra/nginx
      dockerfile: Dockerfile
    working_dir: /var/www
    container_name: kado_nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
    links:
      - php:php
    ports:
      - "80:80"
      - "443:443"
    environment:
      SERVER_NAME: local.kado.com
      ESC: $$
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    networks:
      - network

  # The Database
  db:
    image: mysql:5.7
    container_name: kado_database
    restart: unless-stopped
    tty: true
    volumes:
      - $PWD/scripts/database.sh:/docker-entrypoint-initdb.d/database.sh
      - ./:/var/www
    environment:
      MYSQL_DATABASE: kado
      MYSQL_USER: kado
      MYSQL_PASSWORD: kado
      MYSQL_ROOT_PASSWORD: kado
    expose:
      - 3306
    ports:
      - "3306:3306"
    networks:
      - network

# Docker Networks
networks:
  network:
    driver: bridge
